### ISSUE TITLE
Various Bugs Related to Styles and Core Functionality

### ISSUE THREAD

**Issue by IvoLims** [VueFilesPreview/vue-files-preview#105]
**What happens?**

In the platform I am developing, we allow users to attach various types of files. Currently, whenever a user wants to view a file, they have to download it. We have received requests to implement a preview feature for supported file types. I was excited to come across your project, as it handles many of the file types we use. However, I am encountering several issues.

To provide you with more context, here is the code I have implemented:

```vue
<template>

  <v-dialog
    v-model="show"
    scrollable
    width="90%"
    height="90%">
    <v-card class="preview-attachment-card">
      <Loading
        v-if="isLoadingTranslations || isLoading || isLoadingPreview"
        class="h-100" />
      <template v-else>
        <v-card-title class="d-flex align-center justify-end pa-3">
          <span class="text-h5 text-truncate">{{ t('attachments.preview') }}</span>

          <v-spacer />

          <IdBtn
            color="tertiary"
            icon="mdi-window-close"
            @click="close" />
        </v-card-title>

        <v-divider />

        <v-card-text>
          <vue-files-preview
            v-if="previewIsAvailable"
            ref="vue-files-preview-ref"
            :file="file" />

          <div
            v-else
            class="d-flex flex-column justify-center align-center text-tertiary h-100">
            <IdIcon
              size="x-large"
              icon="mdi-alert-outline"
              color="tertiary" />

            <span class="text-center">
              {{ t('attachments.the-preview-for') }}

              <span class="font-weight-bold text-primary">
                {{ attachment.name }}
              </span>

              {{ t('attachments.is-not-available') }}
              <div>{{ t('attachments.please-download-the-file') }}</div>
            </span>
          </div>
        </v-card-text>

        <v-divider />

        <v-card-actions class="d-flex justify-end pa-3">
          <IdBtn
            :label="t('actions.close')"
            color="secondary"
            size="default"
            @click="close">
          </IdBtn>

          <IdBtn
            class="ml-2"
            :label="t('attachments.download')"
            :disabled="isLoading"
            size="default"
            @click="download">
          </IdBtn>
        </v-card-actions>
      </template>
    </v-card>
  </v-dialog>
  
</template>

<script>
  import Loading from '@/components/local-shared/Loading.vue';
  import IdBtn from '@/components/local-shared/id-components/IdBtn';
  import IdIcon from '@/components/local-shared/id-components/IdIcon';

  import { base64StringToBlob } from 'blob-util';
  import fileSaver from 'file-saver';
  import { VueFilesPreview } from 'vue-files-preview';

  export default {
    name: 'PreviewAttachment',

    emits: ['close'],

    components: {
      Loading,
      VueFilesPreview,
      IdBtn,
      IdIcon
    },

    props: {
      isLoading: {
        type: Boolean,
        default: false
      },
      attachment: {
        type: Object,
        default: null
      }
    },

    data() {
      return {
        show: true,
        file: null,
        attachmentBlob: null,
        isLoadingPreview: true,
        previewIsAvailable: true,

        translationKeys: ['attachments.preview', 'attachments.the-preview-for', 'attachments.please-download-the-file', 'attachments.download']
      };
    },

    methods: {
      close() {
        this.$emit('close');
      },

      checkPreviewStatus() {
        const previewElement = this.$refs['vue-files-preview-ref']?.$el;

        this.previewIsAvailable = previewElement?.children?.length > 0;
      },

      loadFile() {
        this.isLoadingPreview = true;

        this.attachmentBlob = base64StringToBlob(this.attachment.base64);
        this.file = new File([this.attachmentBlob], this.attachment.name, { type: this.attachment.mimeType });

        this.$nextTick(() => {
          this.checkPreviewStatus();
        }, 1000);

        this.isLoadingPreview = false;
      },

      download() {
        fileSaver.saveAs(this.attachmentBlob, this.attachment.name);
      }
    },

    watch: {
      isLoading(newValue) {
        if (!newValue) {
          this.loadFile();
        }
      }
    }
  };
</script>
```

I make a request to my server for a specific file, and the response includes the following information:

```js
this.previewFile = {
  name: attachment.fileName,
  mimeType: attachment.mimeType,
  base64: result.data.data.content
};
```

I am attempting to implement the preview functionality. While the preview works for many file types, there are some types, such as .doc and .xls, that are not included in the list you provide. Consequently, I still have to inform users that they need to download these files. It would be very helpful to have an event or a method that notifies whether a file can be previewed or not. This would eliminate the need to search for child elements within the vue-files-preview div.

```js
checkPreviewStatus() {
  const previewElement = this.$refs['vue-files-preview-ref']?.$el;
  this.previewIsAvailable = previewElement?.children?.length > 0;
}
```
Sometimes, the rendering takes longer, which prevents the preview from being displayed even when it is available.

Additionally, when previewing MP3 files, I receive a console warning: "Failed to resolve component: el-button."

![image](https://github.com/user-attachments/assets/8d328a85-125a-4046-ac90-2eadd97fc510)

It seems that many styles are not being exported correctly. I had to apply the following styles to ensure proper display for almost all file types. I copied some from the demo other are my own.

```scss
.preview-attachment-card {
  .vue-files-preview {
    height: unset !important; /* Ensure it takes at least full height */
    display: flex; /* Use flexbox for centering */
    justify-content: center; /* Center horizontally */
    align-items: center; /* Center vertically */
  }

  .vue-files-preview > div {
    width: 100%; /* Make the inner div take full width */
    display: flex; /* Use flexbox for centering */
    justify-content: center; /* Center horizontally */
    align-items: center; /* Center vertically */
  }

  /* Start - PDF file */
  .vue-files-preview .pdf-iframe {
    width: 100%; /* Full width of the container */
    height: 100vh; /* Full height of the container */
    border: none; /* Remove border around the iframe */
  }
  /* End - PDF file */

  /* Start - Image file */
  .vue-files-preview img {
    max-width: 100%; /* Ensure the image does not exceed the container's width */
    max-height: 100%; /* Ensure the image does not exceed the container's height */
    object-fit: contain; /* Scale the image to maintain aspect ratio */
  }
  /* End - Image file */

  /* Start - Video file */
  .vue-files-preview .web-full-screen {
    width: inherit; /* Inherit width */
    height: 100%; /* Full height */
    overflow: hidden; /* Hide overflow */
  }

  .vue-files-preview .player-video-main {
    width: inherit; /* Inherit width */
    height: 100%; /* Full height */
    overflow: hidden; /* Hide overflow */
  }
  /* End - Video file */

  /* Start - Word file */
  .vue-office-docx {
    width: 100%; /* Full width of the container */
    height: 100%; /* Full height of the container */
    overflow: auto; /* Allow scrolling if content overflows */
    display: flex; /* Use flexbox for layout */
    flex-direction: column; /* Stack children vertically */
  }

  .vue-office-docx-main {
    flex: 1; /* Allow this section to grow and fill available space */
    display: flex; /* Use flexbox for layout */
    justify-content: center; /* Center content horizontally */
    align-items: flex-start; /* Align content to the top */
    padding: 20px; /* Add some padding for better spacing */
    box-sizing: border-box; /* Include padding in width/height calculations */
  }

  @media screen and (max-width: 945px) {
    .vue-office-docx-main {
      width: fit-content; /* Set width to fit content */
    }
  }

  .docx-wrapper {
    background: gray; /* Background color for the wrapper */
    padding: 30px; /* Padding around the content */
    padding-bottom: 0; /* Remove bottom padding */
    display: flex; /* Use flexbox for layout */
    flex-direction: column; /* Stack children vertically */
    align-items: center; /* Center children horizontally */
  }

  .docx {
    color: black; /* Text color */
    hyphens: auto; /* Enable hyphenation */
    text-underline-position: from-font; /* Underline position */
  }

  .docx-wrapper > section.docx {
    background: white; /* Background color for the document section */
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.5); /* Shadow for depth */
    margin-bottom: 30px; /* Space below the document section */
    width: 100%; /* Full width */
    overflow: auto; /* Allow scrolling if content overflows */
  }

  /* Additional styles for the document content */
  .docx p {
    margin: 0; /* Remove default margin */
    min-height: 1em; /* Minimum height for paragraphs */
  }

  .docx table {
    border-collapse: collapse; /* Collapse table borders */
  }

  .docx table td,
  .docx table th {
    vertical-align: top; /* Align table cell content to the top */
  }

  /* Ensure the iframe for PDF is styled correctly */
  .vue-office-docx iframe {
    width: 100%; /* Full width of the container */
    height: 100%; /* Full height of the container */
    border: none; /* Remove border */
  }

  /* End - Word file */

  /* Start - Excel file */

  .x-spreadsheet {
    font-size: 13px;
    line-height: normal;
    -webkit-user-select: none;
    user-select: none;
    -moz-user-select: none;
    font-family:
      Lato,
      Source Sans Pro,
      Roboto,
      Helvetica,
      Arial,
      sans-serif;
    box-sizing: content-box;
    background: #fff;
    -webkit-font-smoothing: antialiased;
  }

  .x-spreadsheet-sheet {
    position: relative;
    overflow: hidden;

    canvas {
      aspect-ratio: auto 1920 / 861;
      overflow-clip-margin: content-box;
      overflow: clip;
    }

    .x-spreadsheet-table {
      vertical-align: bottom;
    }

    .x-spreadsheet-overlayer {
      position: absolute;
      left: 0;
      top: 0;
      z-index: 10;

      .x-spreadsheet-overlayer-content {
        position: absolute;
        overflow: hidden;
        pointer-events: none;

        .x-spreadsheet-editor {
          z-index: 20;

          .x-spreadsheet-editor-area {
            position: absolute;
            text-align: left;
            border: 2px solid #4b89ff;
            line-height: 0;
            z-index: 100;
            pointer-events: auto;

            textarea {
              box-sizing: content-box;
              border: none;
              padding: 0 3px;
              outline: none;
              resize: none;
              text-align: start;
              overflow-y: hidden;
              font:
                400 13px Arial,
                Lato,
                Source Sans Pro,
                Roboto,
                Helvetica,
                sans-serif;
              color: inherit;
              white-space: normal;
              word-wrap: break-word;
              line-height: 22px;
              margin: 0;
            }

            .textline {
              overflow: hidden;
              visibility: hidden;
              position: fixed;
              top: 0;
              left: 0;
            }

            .x-spreadsheet-suggest {
              display: none;
            }

            .x-spreadsheet-datepicker {
              display: none;
            }
          }
        }

        .x-spreadsheet-editor,
        .x-spreadsheet-selector {
          box-sizing: content-box;
          position: absolute;
          overflow: hidden;
          pointer-events: none;
          width: 100%;
          height: 100%;
        }
      }
    }

    .x-spreadsheet-resizer {
      position: absolute;
      z-index: 11;

      .horizontal {
        display: none;
        cursor: row-resize;
      }

      .vertical {
        cursor: col-resize;
      }

      .x-spreadsheet-resizer-hover {
        background-color: #4b89ff40;
      }

      .x-spreadsheet-resizer-line {
        position: absolute;
        border-bottom: 2px dashed #4b89ff;
        left: 0;
        bottom: 0;
      }
    }

    .x-spreadsheet-scrollbar {
      position: absolute;

      right: 0;
      background-color: #f4f5f8;
      opacity: 0.9;
      z-index: 12;

      .vertical {
        bottom: 15px;
        overflow-x: hidden;
        overflow-y: scroll;
      }

      .horizontal {
        right: 15px;
        overflow-x: scroll;
        overflow-y: hidden;
      }
    }
  }

  .x-spreadsheet-print {
    display: none;
  }

  .x-spreadsheet-bottombar {
    position: relative;
    border-top: 1px solid #e0e2e4;
    height: 40px;
    padding: 0 30px;
    text-align: left;
    background: #f5f6f7;
    display: flex;
    .x-spreadsheet-contextmenu {
      display: none;
    }

    .x-spreadsheet-menu {
      display: flex;
      overflow-x: auto;
      list-style: none;
      margin: 0;
      padding: 0;
      -webkit-user-select: none;
      user-select: none;
    }

    .x-spreadsheet-menu > li {
      line-height: 40px;
      height: 40px;
      padding-top: 0;
      padding-bottom: 0;
      vertical-align: middle;
      border-right: 1px solid #e8eaed;
      float: left;

      padding: 0.785em 1em;
      margin: 0;

      text-align: left;

      color: #80868b;
      white-space: nowrap;
      cursor: pointer;
      transition: all 0.3s;
      font-weight: 700;
    }

    .x-spreadsheet-menu li:first-child {
      display: none;
    }

    .x-spreadsheet-menu > li.active {
      background-color: #fff;
      color: #000000a6;
    }
  }

  /* End - Excel file */

  /* Start - Audio file */
  .audio-container {
    width: 100%; /* Full width for audio container */
    display: flex; /* Use flexbox for layout */
    flex-direction: column; /* Stack children vertically */
    align-items: center; /* Center items */
    margin: 1rem 0; /* Add margin for spacing */
  }

  .mp3Box {
    width: 100%; /* Full width for audio box */
    display: flex; /* Use flexbox for layout */
    justify-content: center; /* Center audio player */
    margin: 1rem 0; /* Add margin for spacing */
  }

  audio {
    width: 100%; /* Make audio player full width */
    outline: none; /* Remove default outline */
  }

  el-button {
    display: none;
  }

  .cvs-container {
    display: none;
  }

  /* End - Audio file */

  /* Start - Code file */

  .cm-editor {
    height: 100%;
    width: 100%;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
    overflow: auto;
  }

  .cm-scroller {
    overflow: auto;
    font-size: 14px;
  }

  .cm-lineNumbers {
    padding-right: 10px;
  }

  /* End - Code file */

  /* Start - Markdown file */
  .hljs {
    border-radius: 8px;
    padding: 20px;
  }

  /* Headings */
  .hljs h1 {
    color: #141f40;
    font-size: 2.5rem;
    border-bottom: 2px solid #e6e8ec;
    padding-bottom: 10px;
    margin-bottom: 20px;
  }

  .hljs h2 {
    color: #266cfb;
    font-size: 1.8rem;
    border-bottom: 1px solid #e6e8ec;
    padding-bottom: 8px;
    margin-top: 30px;
    margin-bottom: 15px;
  }

  .hljs h3 {
    color: #227cf2;
    font-size: 1.5rem;
    margin-top: 25px;
    margin-bottom: 10px;
  }

  /* Paragraphs */
  .hljs p {
    color: #333;
    margin-bottom: 15px;
  }

  /* Links */
  .hljs a {
    color: #276bf2;
    text-decoration: none;
    transition: color 0.3s ease;
  }

  .hljs a:hover {
    color: #3079d9;
    text-decoration: underline;
  }

  /* Lists */
  .hljs ul,
  .hljs ol {
    margin-bottom: 15px;
    padding-left: 30px;
  }

  .hljs ul li,
  .hljs ol li {
    margin-bottom: 8px;
  }

  /* Code Blocks */
  .hljs pre {
    background-color: #f6f6f6;
    border-radius: 4px;
    padding: 15px;
    overflow-x: auto;
    margin-bottom: 15px;
  }

  .hljs code {
    font-family: "Fira Code", monospace;
    font-size: 0.9rem;
    color: #141f40;
  }

  /* Color Swatches */
  .hljs img[alt^="#"] {
    width: 15px;
    height: 15px;
    display: inline-block;
    margin-right: 8px;
    vertical-align: middle;
    border-radius: 50%;
  }

  /* End - Markdown file */
}
```

I am also unable to preview `Excel files`, even though they work correctly in the demo. I thought it was something with the styles and indeed many were missing but even after I applied then the canvas for Excel files in my implementation has a very limited height.

![image](https://github.com/user-attachments/assets/2cc8f3dc-81f8-4df4-99b2-2f8886cd8869)

But when I remove the style

```
.preview-attachment-card .x-spreadsheet-sheet {
    position: relative;
    /* overflow: hidden; */
}
```

![image](https://github.com/user-attachments/assets/40b894e7-ceac-4873-aca7-b421b7b78bb0)

For `.txt files`, it would be beneficial if they maintained their default formatting, including tabs, new lines, and multiple spaces. This would greatly enhance the readability of the content.

Preview
![image](https://github.com/user-attachments/assets/713adcb8-5403-4172-b842-bdcd7841cc48)

Original
![image](https://github.com/user-attachments/assets/46d13491-70ca-462e-953a-027b668970b0)

Lastly, I was unable to open the `EPUB file` I attempted to preview (I let it under).

**How To Reproduce**

Just installed and tried using the component

**Context:**

- vue-files-preview Version: "^1.0.37"
- Node Version: "v21.6.1"
- Platform: Desktop
- Vue Version: "^3.5.3"
- Vuetify Version: "3.7.1"

**Files that I am using to test:**

[sample-file.xlsx](https://github.com/user-attachments/files/18361654/sample-file.xlsx)
[Book.xlsx](https://github.com/user-attachments/files/18361655/Book.xlsx)
[Accessible EPUB 3](https://idpf.github.io/epub3-samples/30/samples.html)

I would appreciate any guidance or support you can provide regarding these issues. Thank you!
